// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXSiWObtH9cKtU4PCMaAudkgVQhi19QXo',
    appId: '1:472204912075:web:4fc0ee46d3540f6d1bc24e',
    messagingSenderId: '472204912075',
    projectId: 'fluttertfg-3cec2',
    authDomain: 'fluttertfg-3cec2.firebaseapp.com',
    storageBucket: 'fluttertfg-3cec2.firebasestorage.app',
    measurementId: 'G-BQ1SRYW1DZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPfNJkrTYWvDyBJeixgtDDrVBetxMu-Cg',
    appId: '1:472204912075:android:0cc3a630c9590eb21bc24e',
    messagingSenderId: '472204912075',
    projectId: 'fluttertfg-3cec2',
    storageBucket: 'fluttertfg-3cec2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgu-CLNQ4vmi9fywiPmtK71UIlpYRdwbo',
    appId: '1:472204912075:ios:30c61ec1704019dc1bc24e',
    messagingSenderId: '472204912075',
    projectId: 'fluttertfg-3cec2',
    storageBucket: 'fluttertfg-3cec2.firebasestorage.app',
    iosBundleId: 'com.example.clanBarberClubAndujar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgu-CLNQ4vmi9fywiPmtK71UIlpYRdwbo',
    appId: '1:472204912075:ios:30c61ec1704019dc1bc24e',
    messagingSenderId: '472204912075',
    projectId: 'fluttertfg-3cec2',
    storageBucket: 'fluttertfg-3cec2.firebasestorage.app',
    iosBundleId: 'com.example.clanBarberClubAndujar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXSiWObtH9cKtU4PCMaAudkgVQhi19QXo',
    appId: '1:472204912075:web:3237fe67f3d1be4e1bc24e',
    messagingSenderId: '472204912075',
    projectId: 'fluttertfg-3cec2',
    authDomain: 'fluttertfg-3cec2.firebaseapp.com',
    storageBucket: 'fluttertfg-3cec2.firebasestorage.app',
    measurementId: 'G-SCZKCCNK6P',
  );

}