name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia a tu rama principal si es distinta

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'  # Cambia a la versión que uses

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter web
      run: flutter build web

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./build/web
        user_name: github-actions
        user_email: github-actions@github.com
